return {
	diagnostics = {
		error = " ",
		warn = " ",
		hint = " ",
		info = " ",
	},
	git = {
		added = " ",
		modified = " ",
		removed = " ",
		renamed = "󰜵 ",
		untracked = " ",
		ignored = "",
		unstaged = "󰄱",
		staged = "",
		conflict = "",
	},
	lsp_completions = {
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Enum = " ",
		EnumMember = " ",
		Event = "",
		Field = "󰄶 ",
		File = " ",
		Folder = " ",
		Function = "ƒ ",
		Interface = " ",
		Keyword = "󰌆 ",
		Method = "ƒ ",
		Module = "󰏗 ",
		Operator = " ",
		Property = " ",
		Snippet = "󰘍 ",
		Struct = " ",
		Text = " ",
		Unit = " ",
		Value = "󰎠 ",
		Variable = " ",
	},
}
