return {
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   lazy = true,
  --   event = "VeryLazy",
  --   tag = "0.1.5",
  --   dependencies = {
  --     { "nvim-lua/plenary.nvim" },
  --     {
  --       "nvim-telescope/telescope-fzf-native.nvim",
  --       build = "make",
  --     },
  --     {
  --       "dimaportenko/telescope-simulators.nvim",
  --     },
  --   },
  --   config = function()
  --     local telescope = require("telescope")
  --     telescope.load_extension("fzf")
  --     telescope.load_extension("yank_history")
  --
  --     local telescopeConfig = require("telescope.config")
  --
  --     local vimgrep_arguments = { table.unpack(telescopeConfig.values.vimgrep_arguments) }
  --     table.insert(vimgrep_arguments, "--hidden")
  --     table.insert(vimgrep_arguments, "--glob")
  --     table.insert(vimgrep_arguments, "!**/.git/*")
  --
  --     local actions = require("telescope.actions")
  --     telescope.setup({
  --       pickers = {
  --         colorscheme = {
  --           enable_preview = true,
  --         },
  --         find_files = {
  --           find_command = { "rg", "--files", "--hidden", "--glob", "!**/.git/*" },
  --         },
  --       },
  --       defaults = {
  --         -- wrap_results = true,
  --         vimgrep_arguments = vimgrep_arguments,
  --         appings = {
  --           i = {
  --             ["<esc>"] = actions.close,
  --           },
  --         },
  --       },
  --     })
  --
  --     require("simulators").setup({
  --       android_emulator = true,
  --       apple_simulator = true,
  --     })
  --   end,
  -- },
}
